const data =[
        {
            id:"1",
            name:"Prod1",
            price:"12",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"2",
            name:"Prod2",
            price:"13",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"3",
            name:"Prod2",
            price:"14",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"4",
            name:"Prod2",
            price:"15",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"5",
            name:"Prod2",
            price:"16",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"6",
            name:"Prod2",
            price:"17",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"7",
            name:"Prod2",
            price:"18",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          },
          {
            id:"8",
            name:"Prod2",
            price:"12",
            image:"https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
          }]


export default data;